### ISSUE TITLE
Is this really a wiki ?

### ISSUE THREAD

**Issue by vdegenne** [jamescarlyle/wikid#6]
I like the idea of having an interplanetary wiki that is not governed by any central authority.
But as far as I know IPFS can't run program on the nodes, it's pure hypermedia global sharing.
Could you explain to me how you manage to give everyone's the ability to change the pages on the ipfs protocol ?
You still need a central server to process the page modification requests right ?

**Comment by jamescarlyle** [comment]
Sorry @vdegenne, I'm just reviewing this.

There is no central server to process modifications. This application is just a Svelte/Javascript application running in the browser, together with an IPFS node connected in the peer to peer IPFS network. There are no change permissions (yet) i.e. knowledge of the page's location allows anyone to create a new version of it, but pages naturally have a predecessor chain and so multiple new versions can be forked in parallel.

The neat thing is that although IPFS pages are immutable, and Wiki pages need to change, IPFS can be used to manage change (just as GitHub does).
